### ISSUE TITLE
Support for Thunderbird  78

### ISSUE THREAD

**Issue by tgimj34** [linagora/linshare-plugin-thunderbird#1]
Due to changes in Thunderbird 78, the linshare plugin doesn't work

**Comment by fmartin-linagora** [comment]
Hi,
Thanks for the feedback, the team is currently working on it. For now, we do not have a release date yet. I will keep you informed once we have it.

**Comment by fmartin-linagora** [comment]
Hi,
it was done with the version 2.0.0. We forgot to provide you the feedback. sorry.
Closing the issue.
